name: Login to DockerHub

on:
  workflow_dispatch:
    branches: [ main ]

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
